steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"

- name: "python"
  args: ["-c", "import subprocess; subprocess.run(
                    ['sed', '-i', 's/$_placeholder_/${_AMAZON_RDS_DB_URL}/g', 'app.yaml']
                )"
  ]

substitutions:
    _AMAZON_RDS_DB_URL: PLACEHOLDER_VALUE
