swagger: "2.0"
info:
  title: Notes
  description: Notes app is a universal clipboard, accessible by all my devices
  version: 1.0.0

basePath: /notes/v1/
consumes:
  - application/json
produces:
  - application/json


paths:
  /:
    get:
      tags: [Get Notes]
      operationId: notes.operations.get_notes
      summary: Get all notes
      description: Lists all available notes in the the database
      produces:
        - text/html
      parameters:
        - name: id
          in: query
          type: integer
          required: false
        - name: ret_json
          in: query
          type: boolean
          required: false
      responses:
        200:
          description: Returns a list of the requested notes
          schema:
            $ref: '#/definitions/NotesList'
        401:
          description: Authentication failed
        440:
          description: Session expired, login again
        404:
          description: User does not exist

  /add:
    get:
      tags: [Add]
      operationId: notes.operations.add_note
      summary: Add note
      description: Add a note to the the database
      produces:
        - application/json
      parameters:
        - name: content
          in: query
          required: true
          type: string
      responses:
        200:
          description: Note successfully added
        401:
          description: Authentication failed
        440:
          description: Session expired, login again
        404:
          description: User does not exist


definitions:
  NotesList:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
        datetime:
          type: string
        user:
          type: string
        content:
          type: string
